---
# Lord forgive me for I have sinned.
# TODO: Not this. Please.
- hosts: localhost
  connection: local
  tasks:
    - name: Add host
      add_host:
        name: matomo.thebalanceffxiv.com
        ansible_host: "{{ matomo_ip }}"
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
        groups: matomo

- hosts: matomo
  tasks:
    - name: ping
      ansible.builtin.ping: