name: "Terraform apply"

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    name: "Terraform apply"
    runs-on: ubuntu-latest
    env:
      tf_actions_working_dir: 'terraform'
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    outputs:
      db-ip: "${{ steps.output1.outputs.stdout }}"
      matomo-ip: "${{ steps.output2.outputs.stdout }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Tell the user that fmt failed
        id: fmt-check
        run: echo "terraform fmt failed, please make sure your .tf files are properly formatted before committing."; exit 1
        if: ${{ steps.fmt.outcome == 'failure' }}

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
      # Not nice but it works:tm:
      # TODO: use anisble provider etc
      - name: Terraform output
        id: output1
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform output db-host

      - name: Terraform output
        id: output2
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform output matomo-host

  ansible:
    name: "Ansible stuff"
    needs: terraform-apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: main.yaml
          # Optional, directory where playbooks live
          directory: ./ansible/playbooks/
          # Optional, SSH private key
          key: ${{secrets.SSH_KEY}}
          # Optional, galaxy requirements filepath
          requirements: ../requirements.yml
          # Optional, additional flags to pass to ansible-playbook
          options: |
            -e db_ip=${{ needs.terraform-apply.outputs.db-ip }}
            -e matomo_ip=${{ needs.terraform-apply.outputs.matomo-ip }}